services:
  mongodb:
    image: mongo
    container_name: ms_mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.4
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.4#configuration for more options
            PBF_URL: https://download.geofabrik.de/south-america/bolivia-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/south-america/bolivia-updates/
            NOMINATIM_PASSWORD: root
            THREADS: 4
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb
networks:
  microservices-net:
    driver: bridge
volumes:
  mongo:
  nominatim-data: